// !!!! Urls are case-sensitive !!!!

var customizationConfig = {
    avatarPieces: [
        // Face sizes are in percentages, and state where the face "default" sits on the piece
        // Fully centered inside the box specified
        { url: "assets/avatar/pieces/apple.svg", faceTop: 20, faceLeft: 25, faceWidth: 50, faceHeight: 70, requirements: { wins: 150, losses: 150, timeInGame: 1500000, timeMyTurn: 1500000, piecesPlaced: 1500 } },
        { url: "assets/avatar/pieces/balloon.svg", faceTop: 15, faceLeft: 15, faceWidth: 50, faceHeight: 50 },
        { url: "assets/avatar/pieces/barrel.svg", faceTop: 35, faceLeft: 25, faceWidth: 50, faceHeight: 50 },
        { url: "assets/avatar/pieces/baseball.svg", faceTop: 20, faceLeft: 30, faceWidth: 40, faceHeight: 60 },
        { url: "assets/avatar/pieces/box.svg", faceTop: 30, faceLeft: 25, faceWidth: 50, faceHeight: 40 },
        { url: "assets/avatar/pieces/bunny.svg", faceTop: 50, faceLeft: 25, faceWidth: 50, faceHeight: 40 },
        { url: "assets/avatar/pieces/carton.svg", faceTop: 40, faceLeft: 30, faceWidth: 25, faceHeight: 40 },
        { url: "assets/avatar/pieces/cloud.svg", faceTop: 25, faceLeft: 25, faceWidth: 50, faceHeight: 50 },
        { url: "assets/avatar/pieces/Controller.svg", faceTop: 25, faceLeft: 25, faceWidth: 50, faceHeight: 30 },
        { url: "assets/avatar/pieces/crown.svg", faceTop: 45, faceLeft: 25, faceWidth: 50, faceHeight: 30 },
        { url: "assets/avatar/pieces/cup.svg", faceTop: 45, faceLeft: 25, faceWidth: 50, faceHeight: 40 },
        { url: "assets/avatar/pieces/cupcake.svg", faceTop: 50, faceLeft: 25, faceWidth: 50, faceHeight: 20 },
        { url: "assets/avatar/pieces/eyeball.svg", faceTop: 45, faceLeft: 25, faceWidth: 50, faceHeight: 40 },
        { url: "assets/avatar/pieces/Flower.svg", faceTop: 35, faceLeft: 25, faceWidth: 50, faceHeight: 35 },
        { url: "assets/avatar/pieces/flower2.svg", faceTop: 35, faceLeft: 25, faceWidth: 50, faceHeight: 35 },
        { url: "assets/avatar/pieces/ghost.svg", faceTop: 25, faceLeft: 25, faceWidth: 50, faceHeight: 50 },
        { url: "assets/avatar/pieces/heart.svg", faceTop: 25, faceLeft: 25, faceWidth: 50, faceHeight: 50 },
        { url: "assets/avatar/pieces/icecream2.svg", faceTop: 10, faceLeft: 25, faceWidth: 50, faceHeight: 40 },
        { url: "assets/avatar/pieces/kitty.svg", faceTop: 30, faceLeft: 25, faceWidth: 50, faceHeight: 50 },
        { url: "assets/avatar/pieces/lemon.svg", faceTop: 25, faceLeft: 25, faceWidth: 50, faceHeight: 50 },
        { url: "assets/avatar/pieces/moch.svg", faceTop: 25, faceLeft: 25, faceWidth: 50, faceHeight: 50 },
        { url: "assets/avatar/pieces/mug.svg", faceTop: 42, faceLeft: 15, faceWidth: 50, faceHeight: 40 },
        { url: "assets/avatar/pieces/nose.svg", faceTop: 40, faceLeft: 25, faceWidth: 50, faceHeight: 40 },
        { url: "assets/avatar/pieces/poop.svg", faceTop: 40, faceLeft: 25, faceWidth: 50, faceHeight: 40 },
        { url: "assets/avatar/pieces/skull2.svg", faceTop: 20, faceLeft: 25, faceWidth: 50, faceHeight: 50 },
        { url: "assets/avatar/pieces/taco.svg", faceTop: 35, faceLeft: 25, faceWidth: 50, faceHeight: 30 },
        { url: "assets/avatar/pieces/teddy.svg", faceTop: 35, faceLeft: 25, faceWidth: 50, faceHeight: 50 },
        { url: "assets/avatar/pieces/tooth.svg", faceTop: 25, faceLeft: 25, faceWidth: 50, faceHeight: 45 },
        { url: "assets/avatar/pieces/tophat.svg", faceTop: 20, faceLeft: 25, faceWidth: 50, faceHeight: 30 },
        { url: "assets/avatar/pieces/tree.svg", faceTop: 25, faceLeft: 25, faceWidth: 50, faceHeight: 35 },
        { url: "assets/avatar/pieces/witch.svg", faceTop: 25, faceLeft: 33, faceWidth: 37, faceHeight: 38 },
    ],
    avatarFaces: [
        { url: "assets/avatar/faces/angry.svg" },
        { url: "assets/avatar/faces/cray.svg" },
        { url: "assets/avatar/faces/crayeyes.svg" },
        { url: "assets/avatar/faces/eyes.svg" },
        { url: "assets/avatar/faces/eyes2.svg" },
        { url: "assets/avatar/faces/eyes3.svg" },
        { url: "assets/avatar/faces/eyes4.svg" },
        { url: "assets/avatar/faces/hap.svg" },
        { url: "assets/avatar/faces/Hap2.svg" },
        { url: "assets/avatar/faces/Hap3.svg" },
        { url: "assets/avatar/faces/hap4.svg" },
        { url: "assets/avatar/faces/hap5.svg" },
        { url: "assets/avatar/faces/hap6.svg" },
        { url: "assets/avatar/faces/happi.svg" },
        { url: "assets/avatar/faces/hearthap.svg" },
        { url: "assets/avatar/faces/hee.svg" },
        { url: "assets/avatar/faces/hmm.svg" },
        { url: "assets/avatar/faces/hmm2.svg" },
        { url: "assets/avatar/faces/hmm3.svg" },
        { url: "assets/avatar/faces/hmph.svg" },
        { url: "assets/avatar/faces/hnrgh.svg" },
        { url: "assets/avatar/faces/kitti.svg" },
        { url: "assets/avatar/faces/Laughalt.svg" },
        { url: "assets/avatar/faces/moch.svg" },
        { url: "assets/avatar/faces/nyah.svg" },
        { url: "assets/avatar/faces/nyheh.svg" },
        { url: "assets/avatar/faces/nyheh2.svg" },
        { url: "assets/avatar/faces/nyheh3.svg" },
        { url: "assets/avatar/faces/owo.svg" },
        { url: "assets/avatar/faces/owo2.svg" },
        { url: "assets/avatar/faces/pumkin.svg" },
        { url: "assets/avatar/faces/scared.svg" },
        { url: "assets/avatar/faces/scaredhap.svg" },
        { url: "assets/avatar/faces/scurry.svg" },
        { url: "assets/avatar/faces/spook.svg" },
        { url: "assets/avatar/faces/spook2.svg" },
        { url: "assets/avatar/faces/spookihap.svg" },
        { url: "assets/avatar/faces/spookihap2.svg" },
        { url: "assets/avatar/faces/spookihap3.svg" },
        { url: "assets/avatar/faces/spookihap4.svg" },
        { url: "assets/avatar/faces/stars.svg" },
        { url: "assets/avatar/faces/ugh.svg" },
	{ url: "assets/avatar/faces/ugh2.svg" },
        { url: "assets/avatar/faces/uwu.svg" },
        { url: "assets/avatar/faces/wheat.svg" },
        { url: "assets/avatar/faces/pika.svg" },
        { url: "assets/avatar/faces/thonk.svg" },
        { url: "assets/avatar/faces/hap7.svg" },
        { url: "assets/avatar/faces/harts.svg" },
        { url: "assets/avatar/faces/mochpbbt.svg" },
        { url: "assets/avatar/faces/nyah2.svg" },
        { url: "assets/avatar/faces/sprakle.svg" },
        { url: "assets/avatar/faces/ara.svg" },
        { url: "assets/avatar/faces/stars2.svg" },
        { url: "assets/avatar/faces/cool.svg" },
        { url: "assets/avatar/faces/xox.svg" },
        { url: "assets/avatar/faces/SMIL.svg" },
        { url: "assets/avatar/faces/myan2.svg" },
        { url: "assets/avatar/faces/myan.svg" },
        { url: "assets/avatar/faces/anime.svg" },
    ]
};